package com.murali.springboot.swagger.api.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * @author:Sanapala Muralidharan
 * @date:Jul 18, 2021 12:34:03 AM
 * @version:2.x
 */
@Entity
@Table
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Book implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -99007167067095984L;
    @Id
    @GeneratedValue
    @ApiModelProperty(value = "autogenerated id")
    private int bookId;
    @ApiModelProperty(value = "this is the book name")
    private String bookName;
    @ApiModelProperty(value = "this is book price")
    private double price;

}
